export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const SET_TOP_RATED_MOVIES = "SET_TOP_RATED_MOVIES";
export const SET_UPCOMING_MOVIES = "SET_UPCOMING_MOVIES";
export const SET_SEARCH_MOVIES = "SET_SEARCH_MOVIES";
export const SET_DETAILS_MOVIE = "SET_DETAILS_MOVIE";
